#ifndef _PROTOCOL_V1_DEFINE_H_
#define _PROTOCOL_V1_DEFINE_H_

#include <stdint.h>

#define PROPOCOL_V1_HEADER_A (0XAA)
#define PROPOCOL_V1_HEADER_B (0XBB)

typedef enum
{
	V1_CMD_SET_DEBUG 							= 0,
	V1_CMD_SET_SENSOR 							= 1,	
	V1_CMD_SET_NUM,	
}PROTOCOL_V1_CMD_SET;

typedef enum
{
	V1_CMD_ID_DEBUG_STRING						= 0,				
	V1_CMD_ID_DEBUG_FLOAT3_1					= 1,
	V1_CMD_ID_DEBUG_FLOAT3_2					= 2,
	V1_CMD_ID_DEBUG_FLOAT3_3					= 3,
	V1_CMD_ID_DEBUG_FLOAT3_4					= 4,
	V1_CMD_ID_DEBUG_FLOAT3_5					= 5,
	V1_CMD_ID_DEBUG_FLOAT4_1					= 6,
	V1_CMD_ID_DEBUG_FLOAT4_2					= 7,
	V1_CMD_ID_DEBUG_FLOAT4_3					= 8,
	V1_CMD_ID_DEBUG_FLOAT4_4					= 9,
	V1_CMD_ID_DEBUG_FLOAT4_5					= 10,
	V1_CMD_ID_DEBUG_FLOAT6_1					= 11,
	V1_CMD_ID_DEBUG_FLOAT6_2					= 12,
	V1_CMD_ID_DEBUG_FLOAT6_3					= 13,
	V1_CMD_ID_DEBUG_FLOAT6_4					= 14,
	V1_CMD_ID_DEBUG_FLOAT6_5					= 15,
	V1_CMD_ID_DEBUG_FLOAT8_1					= 16,
	V1_CMD_ID_DEBUG_FLOAT8_2					= 17,
	V1_CMD_ID_DEBUG_FLOAT8_3					= 18,
	V1_CMD_ID_DEBUG_FLOAT8_4					= 19,
	V1_CMD_ID_DEBUG_FLOAT8_5					= 20,
	V1_CMD_ID_DEBUG_NUM,
}PROTOCOL_V1_CMD_SET_ID_DEBUG;
 
typedef enum
{
	V1_CMD_ID_SENSOR_IMU						= 0,	
	V1_CMD_ID_SENSOR_BARO						= 1,
	V1_CMD_ID_SENSOR_GYR						= 2,
	V1_CMD_ID_SENSOR_ACC						= 3,
	V1_CMD_ID_SENSOR_GYRI16						= 4,
	V1_CMD_ID_SENSOR_ACCI16						= 5,
	V1_CMD_ID_SENSOR_COMPASS					= 6,
	V1_CMD_ID_SENSOR_COMPASSI16					= 7,
	V1_CMD_ID_SENSOR_GPS_POSLLH					= 8,
	V1_CMD_ID_SENSOR_GPS_STATUS					= 9,
	V1_CMD_ID_SENSOR_GPS_SOL					= 10,
	V1_CMD_ID_SENSOR_GPS_VELNED					= 11,	
	V1_CMD_ID_SENSOR_RC_RAW						= 12,	
	V1_CMD_ID_SENSOR_IMUI16						= 13,	
	V1_CMD_ID_SENSOR_COMPASS_EXT 				= 14,
	V1_CMD_ID_SENSOR_COMPASSI16_EXT				= 15,
	V1_CMD_ID_SENSOR_CAMERA_TRIG				= 16,	
	V1_CMD_ID_SENSOR_BATTERY					= 17,	
	V1_CMD_ID_SENSOR_NUM,
}PROTOCOL_V1_CMD_SET_ID_SENSOR;




#ifdef __cplusplus
 extern "C" {
#endif

#ifdef __cplusplus
 }
#endif

#endif
 
